### ISSUE TITLE
Connections with sys_effect doesn't work

### ISSUE THREAD

**Issue by SrMouraSilva** [PedalPi/PluginsManager#9]
For test https://gist.github.com/SrMouraSilva/f7a3904f3984bcaec7e15c60039bc3c3

# Error 1

## Description
```python
> sys_effect.outputs[0].connect(reverb.inputs[0])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/output.py", line 63, in connect
    self.effect.pedalboard.connections.append(Connection(self, effect_input))
AttributeError: 'NoneType' object has no attribute 'connections'
```

## Cause

This error occurs because of the fact that system_effects can not be added to pedalboards

## Other method for use

If this error is occurring with you, the following method works.

```python
# For connect output system effects, use
pedalboard.connections.append(Connection(sys_effect.outputs[0], reverb.inputs[0]))
# Instead of
#sys_effect.outputs[0].connect(reverb.inputs[0])
```

#

**Comment by SrMouraSilva** [comment]
# Error 2

```
pedalboard.connections.append(reverb2.outputs[0].connect(sys_effect.inputs[0]))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/util/observable_list.py", line 38, in append
    self.observer(UpdateType.CREATED, item, len(self._list)-1)
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/pedalboard.py", line 94, in _connections_observer
    self.observer.on_connection_updated(connection, update_type)
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/banks_manager.py", line 143, in on_connection_updated
    observer.on_connection_updated(connection, update_type)
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/mod_host/mod_host.py", line 165, in on_connection_updated
```
